server:
  port: 5000
spring:  application:    name: zuul-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka,http://localhost:6003/eureka #Eureka Server注册服务的地址           
zuul:  routes:    good:
      path: /service-goods/**
      service-id: GOODS-PROVIDER
                